"""Step 5: build the merged Set 2 training sets = Isaac synthetic + real captures.

Same philosophy as Set 1's merge_classifier_data.py: synthetic supplies pose/angle
coverage at scale, the real (ArUco-composited + blank-cube) data supplies true
appearance, and REAL data is oversampled so it is not drowned. Validation uses REAL
data only, so val metrics reflect the deployment domain.

  classifier: datasets/set2/classifier  + datasets/set2_real/classifier
              -> datasets/set2_merged/classifier/{train,val}/<class>/     (symlinks)
  detector:   datasets/set2/detector    + datasets/set2_real/detector
              -> datasets/set2_merged/detector/{images,labels}/{train,val}
              + configs/set2_detector_merged.yaml

    yolo/bin/python training/merge_set2_data.py --repeat 2 --det-repeat 2
    yolo/bin/python training/train_set2_classifier.py --data datasets/set2_merged/classifier
    yolo/bin/python training/train_set2_detector.py   --data configs/set2_detector_merged.yaml \
        --model models/set2/detector/best.pt          # fine-tune from the synthetic model
"""

import argparse
import glob
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "configs"))
from set2_classes import CLASSIFIER_CLASSES  # noqa: E402

SYN_C = os.path.join(ROOT, "datasets", "set2", "classifier")
REAL_C = os.path.join(ROOT, "datasets", "set2_real", "classifier")
SYN_D = os.path.join(ROOT, "datasets", "set2", "detector")
REAL_D = os.path.join(ROOT, "datasets", "set2_real", "detector")
OUT = os.path.join(ROOT, "datasets", "set2_merged")
DET_YAML = os.path.join(ROOT, "configs", "set2_detector_merged.yaml")


def link(src, dst):
    if not os.path.exists(dst):
        os.symlink(os.path.abspath(src), dst)


def merge_classifier(repeat, syn_cap):
    out = os.path.join(OUT, "classifier")
    stats = {}
    for c in CLASSIFIER_CLASSES:
        # train = capped synthetic + repeated real; val = REAL ONLY
        d = os.path.join(out, "train", c)
        os.makedirs(d, exist_ok=True)
        syn = sorted(glob.glob(os.path.join(SYN_C, "train", c, "*")))[:syn_cap]
        for f in syn:
            link(f, os.path.join(d, "syn_" + os.path.basename(f)))
        real = sorted(glob.glob(os.path.join(REAL_C, "train", c, "*")))
        for k in range(repeat):
            for f in real:
                link(f, os.path.join(d, f"r{k}_" + os.path.basename(f)))
        dv = os.path.join(out, "val", c)
        os.makedirs(dv, exist_ok=True)
        realv = sorted(glob.glob(os.path.join(REAL_C, "val", c, "*")))
        for f in realv:
            link(f, os.path.join(dv, os.path.basename(f)))
        stats[c] = (len(syn), len(real), repeat, len(realv))
    print("classifier (train: syn + real x repeat | val: real only)")
    for c, (s, r, k, v) in stats.items():
        print(f"  {c:<10} train {s} syn + {r}x{k} real = {s + r * k:>6}   val {v}")


def merge_detector(repeat, syn_cap):
    for sub in ("images", "labels"):
        for split in ("train", "val"):
            os.makedirs(os.path.join(OUT, "detector", sub, split), exist_ok=True)

    def pair_link(img, prefix, split):
        stem = os.path.splitext(os.path.basename(img))[0]
        lbl = os.path.join(os.path.dirname(img).replace(
            f"{os.sep}images{os.sep}", f"{os.sep}labels{os.sep}"), stem + ".txt")
        if not os.path.exists(lbl):
            return 0
        link(img, os.path.join(OUT, "detector", "images", split,
                               prefix + os.path.basename(img)))
        link(lbl, os.path.join(OUT, "detector", "labels", split,
                               prefix + stem + ".txt"))
        return 1

    n_syn = sum(pair_link(f, "syn_", "train") for f in sorted(
        glob.glob(os.path.join(SYN_D, "images", "train", "*")))[:syn_cap])
    real_tr = sorted(glob.glob(os.path.join(REAL_D, "images", "train", "*")))
    n_real = sum(pair_link(f, f"r{k}_", "train")
                 for k in range(repeat) for f in real_tr)
    n_val = sum(pair_link(f, "", "val") for f in sorted(
        glob.glob(os.path.join(REAL_D, "images", "val", "*"))))
    print(f"detector   train {n_syn} syn + {n_real} real (x{repeat})   "
          f"val {n_val} (real only)")

    with open(DET_YAML, "w") as f:
        f.write("# Merged Set 2 detector data: synthetic + real (val = real only).\n"
                "# Generated by training/merge_set2_data.py\n"
                f"path: {os.path.join(OUT, 'detector')}\n"
                "train: images/train\nval: images/val\n"
                "names:\n  0: cube_candidate\n")
    print("wrote", os.path.relpath(DET_YAML, ROOT))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repeat", type=int, default=2,
                    help="oversample factor for real classifier crops")
    ap.add_argument("--syn-cap", type=int, default=3000,
                    help="max synthetic classifier crops per class")
    ap.add_argument("--det-repeat", type=int, default=2,
                    help="oversample factor for real detector frames")
    ap.add_argument("--det-syn-cap", type=int, default=6000,
                    help="max synthetic detector frames")
    args = ap.parse_args()

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    merge_classifier(args.repeat, args.syn_cap)
    merge_detector(args.det_repeat, args.det_syn_cap)


if __name__ == "__main__":
    main()
